import type { LeaderboardEntry } from '@/types'

/**
 * MOCK leaderboard data.
 * Replace with a real fetch from your backend/DB once it's ready.
 * This lives in lib/ so the homepage Server Component can import it directly
 * without an HTTP round-trip.
 */
export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  {
    id: 'usr_001',
    name: 'Yuki Tanaka',
    avatar: 'https://api.dicebear.com/8.x/bottts-neutral/svg?seed=yuki',
    rank: 1,
    score: 24810,
    challengesCompleted: 31,
    totalCO2Saved: 128400,
    topLanguage: 'Rust',
    delta: 'same',
  },
  {
    id: 'usr_002',
    name: 'Fatima Al-Hassan',
    avatar: 'https://api.dicebear.com/8.x/bottts-neutral/svg?seed=fatima',
    rank: 2,
    score: 21340,
    challengesCompleted: 27,
    totalCO2Saved: 109700,
    topLanguage: 'Go',
    delta: 'up',
  },
  {
    id: 'usr_003',
    name: 'Marcus Oliveira',
    avatar: 'https://api.dicebear.com/8.x/bottts-neutral/svg?seed=marcus',
    rank: 3,
    score: 19200,
    challengesCompleted: 24,
    totalCO2Saved: 98100,
    topLanguage: 'TypeScript',
    delta: 'up',
  },
  {
    id: 'usr_004',
    name: 'Priya Nair',
    avatar: 'https://api.dicebear.com/8.x/bottts-neutral/svg?seed=priya',
    rank: 4,
    score: 17850,
    challengesCompleted: 22,
    totalCO2Saved: 87300,
    topLanguage: 'Python',
    delta: 'down',
  },
  {
    id: 'usr_005',
    name: 'Lena Becker',
    avatar: 'https://api.dicebear.com/8.x/bottts-neutral/svg?seed=lena',
    rank: 5,
    score: 15990,
    challengesCompleted: 20,
    totalCO2Saved: 76200,
    topLanguage: 'C++',
    delta: 'same',
  },
  {
    id: 'usr_006',
    name: 'James Oduya',
    avatar: 'https://api.dicebear.com/8.x/bottts-neutral/svg?seed=james',
    rank: 6,
    score: 14400,
    challengesCompleted: 18,
    totalCO2Saved: 65800,
    topLanguage: 'Java',
    delta: 'up',
  },
  {
    id: 'usr_demo_001', // matches the mock user from /api/user
    name: 'Alex Chen',
    avatar: 'https://api.dicebear.com/8.x/bottts-neutral/svg?seed=leafcode-alex',
    rank: 7,
    score: 9240,
    challengesCompleted: 14,
    totalCO2Saved: 48320,
    topLanguage: 'Python',
    delta: 'up',
  },
  {
    id: 'usr_008',
    name: 'Sofia Reyes',
    avatar: 'https://api.dicebear.com/8.x/bottts-neutral/svg?seed=sofia',
    rank: 8,
    score: 8100,
    challengesCompleted: 11,
    totalCO2Saved: 39400,
    topLanguage: 'Kotlin',
    delta: 'down',
  },
  {
    id: 'usr_009',
    name: 'Tao Zhang',
    avatar: 'https://api.dicebear.com/8.x/bottts-neutral/svg?seed=taozhang',
    rank: 9,
    score: 6750,
    challengesCompleted: 9,
    totalCO2Saved: 31200,
    topLanguage: 'Go',
    delta: 'same',
  },
  {
    id: 'usr_010',
    name: 'Elena Petrov',
    avatar: 'https://api.dicebear.com/8.x/bottts-neutral/svg?seed=elena',
    rank: 10,
    score: 5400,
    challengesCompleted: 7,
    totalCO2Saved: 22800,
    topLanguage: 'Rust',
    delta: 'down',
  },
]